[package]
name = "discv4"
version = "0.1.0"
license = "Apache-2.0"
authors = [
    "Artem Vorotnikov <artem@vorotnikov.me>",
    "Wei Tang <hi@that.world>",
]
description = "Ethereum's Node Discovery v4."
repository = "https://github.com/rust-ethereum/discv4"
edition = "2018"

[dependencies]
anyhow = "1"
array-init = "1.0.0"
arrayref = "0.3"
arrayvec = "0.5.1"
async-trait = "0.1"
bytes = "0.5"
chrono = "0.4"
enum-primitive-derive = "0.2.1"
fixed-hash = { version = "*", features = ["std"] }
futures = "0.3"
hex = "0.4.2"
igd = { version = "0.11", features = ["aio"] }
k256 = { version = "0.5", default-features = false, features = ["ecdsa"] }
num-traits = "0.2.12"
parking_lot = "0.11"
plain_hasher = "0.2.3"
primitive-types = { version = "0.7", default-features = false, features = ["rlp"] }
rand = "0.7"
rlp = { version = "0.4", features = ["arrayvec"] }
rlp-derive = "0.1"
sha3 = "0.9"
signature = { version = "1", features = ["std"] }
task-group = { git = "https://github.com/vorot93/task-group" }
thiserror = "1"
tokio = { version = "0.2", features = ["net", "rt-core"] }
tokio-util = { version = "0.3", features = ["codec", "udp"] }
tracing = "0.1"
tracing-futures = "0.2"
url = "2"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
tracing-subscriber = "0.2"

[patch.crates-io]
rlp = { git = "https://github.com/vorot93/parity-common", branch = "arrayvec" }
