[package]
name = "discv4"
version = "0.1.0"
license = "Apache-2.0"
authors = [
    "Artem Vorotnikov <artem@vorotnikov.me>",
    "Wei Tang <hi@that.world>",
]
description = "Ethereum's Node Discovery v4."
repository = "https://github.com/rust-ethereum/discv4"
edition = "2018"

[dependencies]
chrono = "0.4"
etcommon-bigint = "0.2"
etcommon-rlp = "0.2"
futures = "0.1"
k256 = { version = "0.5", default-features = false, features = ["ecdsa"] }
rand = "0.7"
sha3 = "0.9"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer-plus = "0.1"
tracing = "0.1"
url = "2"

[dev-dependencies]
tracing-subscriber = "0.2"
